name: Deploy to Oracle Cloud Kubernetes Engine (OKE)

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_REPO: 'tiagohique/myapprunner'
      IMAGE_TAG: 'latest'
      K8S_DEPLOYMENT: 'myapprunner-deployment'
      K8S_NAMESPACE: 'default'

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for ARM64
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64
          tags: ${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }}
          push: true

      - name: Install Oracle CLI
        run: |
          sudo apt update
          sudo apt install -y unzip
          curl -LO https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
          bash install.sh --accept-all-defaults --install-dir ~/bin
          echo 'export PATH=~/bin:$PATH' >> ~/.bashrc
          source ~/.bashrc
        shell: bash

      - name: Configure Oracle CLI
        env:
          OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
          OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_TENANCY: ${{ secrets.OCI_TENANCY }}
          OCI_USER: ${{ secrets.OCI_USER }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
        run: |
          mkdir -p ~/.oci
          echo "$OCI_PRIVATE_KEY" | base64 --decode > ~/.oci/oci_api_key.pem
          echo "[DEFAULT]
          user=$OCI_USER
          fingerprint=$OCI_FINGERPRINT
          tenancy=$OCI_TENANCY
          region=$OCI_REGION
          key_file=~/.oci/oci_api_key.pem" > ~/.oci/config

      - name: Set up Kubernetes config
        run: |
          source ~/.bashrc
          oci ce cluster create-kubeconfig --cluster-id ${{ secrets.OKE_CLUSTER_ID }} --file ~/.kube/config --region $OCI_REGION --token-version 2.0.0
          kubectl config use-context $K8S_NAMESPACE

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/deployment.yaml

      - name: Update Deployment Image
        run: |
          kubectl set image deployment/$K8S_DEPLOYMENT $K8S_DEPLOYMENT=$DOCKER_REPO:$IMAGE_TAG -n $K8S_NAMESPACE
          kubectl rollout status deployment/$K8S_DEPLOYMENT -n $K8S_NAMESPACE
