name: Deploy to Oracle Cloud Kubernetes Engine (OKE)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_REPO: 'tiagohique/myapprunner'
      IMAGE_TAG: 'latest'
      K8S_DEPLOYMENT: 'myapprunner-deployment'
      K8S_NAMESPACE: 'default'

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }}
          push: true

      - name: Set up Oracle Cloud CLI
        uses: oracle/oci-cli-action@v1
        with:
          oci-config-file: ~/.oci/config
          oci-key-file: ~/.oci/oci_api_key.pem
          fingerprint: ${{ secrets.OCI_FINGERPRINT }}
          private-key: ${{ secrets.OCI_PRIVATE_KEY }}
          tenancy: ${{ secrets.OCI_TENANCY }}
          user: ${{ secrets.OCI_USER }}
          region: ${{ secrets.OCI_REGION }}

      - name: Set up Kubernetes config
        run: |
          oci ce cluster create-kubeconfig --cluster-id ${{ secrets.OKE_CLUSTER_ID }} --file ~/.kube/config --region $OCI_REGION --token-version 2.0.0
          kubectl config use-context $K8S_NAMESPACE

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml  # Aplica o Service primeiro para garantir conectividade
         

      - name: Update Deployment Image
        run: |
          kubectl set image deployment/$K8S_DEPLOYMENT $K8S_DEPLOYMENT=$DOCKER_REPO:$IMAGE_TAG -n $K8S_NAMESPACE
          kubectl rollout status deployment/$K8S_DEPLOYMENT -n $K8S_NAMESPACE
